#!/bin/bash

## Define Database for ...
declare -a arr=(	
			"Wennd merksch, dass d Initiale (H.P.S.) vom Hanspi zemli bitter ironisch sind. (N.S)"
			"Manchmal schicke ich ne Karte, manchmal ficke ich ne Schwarze (Faber)"
			"Ide Pfadi heissi Tarantula (B.)"
			"Nico esche en Meitschischmöker (E.v.D)"
			"Dä het no meh Fingerspitzegfühl als der Hanspi (?)"
			"Isch de Bode zhart, isch de Pfader z'zart (Pfnüsu)"
			"Bisch du Behindert? (E.v.D)"
			"Dini Mueter isch Fett (I.)"
			"Sächsi tram (M.M)"
			"Liiiiiiimes von iiiiiiiiiix gegen Unendlich IIIIIntegral ... (C.B)"
			"Soory habe gespritzt (Asi Türk)"
			"Bombe ider Fläsche (Asi Türk)"
			"Die Flasche unter der Kurve (R.M)"
			"Das ultimative Lachen (S.S)"
			"Wer hat am Mittwoch Geburtstag? (L.H)"
			"Hey figger Wigger alles Stief? (E.v.D)"
			"Gange hüt no go Chüe mobbe (D.H)"
			"Du bist zwar erst sechzehn, komm wir drehen Sexszenen (Faber)"
			"Was isch en Lauch im Tornado? (E.v.D)"
			"So jetzt wäri en guete Moment zum wider Synchronisiere (H.S)"
			"Hey säg mol öppis Gschits (I.P)"
			"Mini Herre das isch de Trüc (D.J)""Warum Note? (R.M.)" 
			"Guten Tag Herr Christoph :-) (D.A.)"
			"Wissen Sie überhaupt, wie der Winkel definiert ist?! (P.N.)"
			"Totale Überforderung der Studis. (P.N.)"
			"Sklave des Tools! (P.N.)"
			"pspice - It's pspicier (P.B)"
			"Grad Patent amelde. (P.N.)"
                	"Und jetzt kommt der Moment, in dem der Frosch in Wasser sprint und sein Leben riskiert. (R.G.)"
			"Yes Yes (R.G.)"
			"check - check - double check (R.G.)"
			"bätsch bätsch (R.G.)"
			"Mit dem chamer chlini Chind verschrecke! (R.G.)"
			"Audi-Max und -Moritz. (M.M.)"
			"Guten Nachmittag miteinander. (H.P.S.)"
			"Wiksed Sie witer! (H.P.S.)"
			"Was macht ein Lauch im Wind? (E.v.D.)"
			"Sind Sie Tessiner? (S.W.)"
			"Simulieren ist wirtschaftlich und macht spass? (S.W.)"
			"Gioconda (C.B.)"
			"Nö i bi elektro-sicherheitsberater ^^ Und bald Ingenieur :p. (Kaktus)"
			"Hei Grossmuetter vom Severin alles alles gueti zum geburi. (Sklaven des Tools)"
			"Dini Mueter isch so Fett, me gset se usem All. (?)"
			"Spile mer es Risiko? (R.v.D)"
			"Isch sLäbe guet (R.G)"
                )

## Find Database lenght ...
ARR_LENGHT=${#arr[@]}

if [ -z $1 ]; then
	## Choose a randoom entry ...
	RAND_NUMB=$(( ( RANDOM % $ARR_LENGHT )  + 1))-1

	## Give out ...
	echo "${arr[$RAND_NUMB]}"
else

	if [ "$1" = "-all" ]; then

		for (( i=0; i<=$ARR_LENGHT; i++ ))
		do
			## Give out ...
			echo "${arr[i]}"
			echo "   "			
		done
	else

		## now loop through the above array
		for i in "${arr[@]}"
		do
		  	if [[ $i = *$1* ]]; then
				echo $i
				echo "   "
			fi
		done

	fi

fi










